<script lang="ts">
    import svelteLogo from '../assets/svelte.svg';
</script>

<img src={svelteLogo} alt="svelte logo" class="ml-auto mr-auto h-20" />
<p>The very thing this is. I have wanted to have a personal site for a while, in the off chance it helps me in any way for job recruitment, and saw this as the perfect chance to learn Svelte as well.</p>
<ul class="list-disc list-inside">
    <li>Svelte frontend</li>
    <li>Implemented a <b>CI/CD</b> pipeline using <b>GitHub Actions</b> to automatically build and deploy the website</li>
    <li>For a later project I autogenerated the experience and project descriptions on this site using my resume</li>
</ul>
<ul class="flex space-x-2 my-2">
    <li class="text-xs px-2 py-1 rounded bg-blue-500">TypeScript</li>
    <li class="text-xs px-2 py-1 rounded bg-blue-500">Svelte</li>
</ul>
<p class="text-right text-gray-700 text-sm font-semibold">July 2023 &#8212; August 2023</p>