name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          cargo install wasm-pack
          npm install
      - name: Build
        run: |
          wasm-pack build --target web
          npm run build
          cp -r ./dist/ ./docs/
      - name: Check for Changes
        run: git status
      - name: Commit Changes
        run: |
          git config --local user.name "deploy-bot"
          git add ./docs
          git commit -m "Auto build target."
      - name: Push Changes
        run: git push